language: php
php:
    - 5.5
    - 5.6
before_script:
    - composer install --no-interaction --prefer-dist
script:
    - vendor/bin/phpunit --coverage-clover=coverage.clover
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    - rm coverage.clover
